server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/travel_journal
spring.datasource.username=travel
spring.datasource.password=travel

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
